### PR TITLE
Fix arguments not being passed to sqlcmd

### LINKED ISSUE #144: arguments not passing variable to sqlcmd
I have the following action:
```
uses: azure/sql-action@v2
with:
  connection-string: ${{ secrets.CONNECTION_STRING }}
  path: './test.sql'
  arguments: '-v client_name="testname"'
```
According to the documentaiton, this should pass the arguments to the SQLCMD utility but it's not working.  The line below shows the sqlcmd statement from the logs and there is no -v option.
`sqlcmd -S sqldb-***.database.windows.net -d Auth -U *** -i ./test.sql`

I also get this error when the script runs.
`'client_name' scripting variable not defined.`

This is what the [documentation ](https://github.com/Azure/sql-action#arguments)says:
go-sqlcmd: go-sqlcmd parameters are passed to the go-sqlcmd utility from the arguments property. This enables SQLCMD variables -v to be passed to scripts as seen in the sqlcmd documentation.

### PR DESCRIPTION
**Pull request by emil-eklund**
Updates input-parsing to include additional arguments for `.sql`-file actions.

Fixes #144

### CODE REVIEW

**Comment by emil-eklund** [comment]
@zijchen I am new to developing Github Actions so I was not certain how I could test this change. I have verified that it compiles, but beyond that I am not sure. I did not find any development instructions in this repository.

Please let me know if I can assist in the review/testing of this PR.

**Comment by emil-eklund** [comment]
I noticed that the bug already was present in the PR-check pipeline.
The clean-up process fails for this very reason (though it does not seem to break the pipeline)

https://github.com/Azure/sql-action/actions/runs/3200277752/jobs/5240294743#step:9:60

**Comment by zijchen** [comment]
Thank you for the PR, this looks like a pretty bad bug we missed. I'll add some tests for this after it's merged in.

**Review by zijchen — APPROVED** [review]

**Comment by emil-eklund** [comment]
@zijchen @dzsquared When can we expect this update to reach the Actions Marketplace? 
Is there anything I can help out with that will get it there quicker?

My actions are still exhibiting symptoms and I would like to avoid using a local version.

**Comment by dzsquared** [comment]
now shipped in https://github.com/Azure/sql-action/releases/tag/v2.1

**Pull request merged**
